version: '3'

services:
  unfederated-porter:
    restart: on-failure
    image: nucypher/porter:lynx
    container_name: unfederated-porter
    ports:
      # Default Porter port
      - "80:9155"
    volumes:
      - .:/code
      - ~/.local/share/nucypher:/nucypher
    command: ["nucypher-porter", "run",
              "--eth-provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}",
              "--allow-origins", "${PORTER_CORS_ALLOW_ORIGINS}"]  # empty string if env var not defined which translates to CORS not enabled by default
